#ifndef CRYPTO_TOOLS_ERRORS_H
#define CRYPTO_TOOLS_ERRORS_H

#include "Cryptanalysis/Common/crypto_tools_types.h"

typedef uint32_t CryptoToolsErrorT;

#define CRYPTO_TOOLS_NO_ERROR                       (0u)

#define CRYPTO_TOOLS_ERROR_CLASS_PARAM              (0x80000000u)
#define CRYPTO_TOOLS_EROOR_CLASS_INTERNAL           (0x40000000u)

#define CRYPTO_TOOLS_ERROR_PARAM_INVALID_LENGTH     CRYPTO_TOOLS_ERROR_CLASS_PARAM | (0x01u)
#define CRYPTO_TOOLS_ERROR_PARAM_NULL_PTR           CRYPTO_TOOLS_ERROR_CLASS_PARAM | (0x02u)


#define CRYPTO_TOOLS_ERROR_NO_CIPHER_TEXT           CRYPTO_TOOLS_EROOR_CLASS_INTERNAL | (0x01u)
#define CRYPTO_TOOLS_ERROR_CIPHER_TEXT_CHANGED      CRYPTO_TOOLS_EROOR_CLASS_INTERNAL | (0x02u)
#define CRYPTO_TOOLS_ERROR_NO_ANALYSIS              CRYPTO_TOOLS_EROOR_CLASS_INTERNAL | (0x03u)

#endif // CRYPTO_TOOLS_ERRORS_H
